# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_pic',
            field=models.ImageField(default=b'pic_folder/None/no-img.jpg', upload_to=b'pic_folder/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.CharField(max_length=20000),
        ),
    ]
